name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --filter '*'

      - name: Build
        run: bun run build

      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
